### ISSUE TITLE
Autocomplete function for places not working in webtrees 2.1.2

### ISSUE THREAD

**Issue by TheDutchJewel** [tkempf/autocomplete_place_location#1]
The autocomplete function for places does not work in webtrees 2.1.2.

Tested with latest version of this module (2.1.0-alpha2).

See [this forum topic](https://www.webtrees.net/index.php/en/forum/help-for-release-2-1-x/36881-search-advance-search).

**Comment by tkempf** [comment]
It works in my 2.1.2 installation. Could you  please provide some more information about the error you see ?

**Comment by TheDutchJewel** [comment]
>Could you please provide some more information about the error you see?

There is no error.

The module is enabled, all other modules disabled and autocomplete for places in webtrees edit fields in place of BIRT/DEAT/MARR works fine.

But in the **Advanced search** function the autocomplete for locations does not work.

**Comment by tkempf** [comment]
I can confirm this behaviour. It looks to me as if the Module Hook does not get called for those fields, which means this is not a problem with this module, This is more an issue of webtrees itself. I close it here, as there is already the issue [github.com/fisharebest/webtrees/issues/4406](https://github.com/fisharebest/webtrees/issues/4406)
